### ISSUE TITLE
WS2812 LED is disabled

### ISSUE THREAD

**Issue by randallgyebi** [espressif/esp-jumpstart#13]
I keep getting this message in the terminal whenever I try to flash the ESP32. Just wondering if this is standard

`W (297) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (311) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (322) gpio: GPIO[0]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 
I (332) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
W (342) ws2812_led: WS2812 LED is disabled
`

**Comment by shahpiyushv** [comment]
The WS2812 LED support was recently added just for better demonstration with the development boards. However, the LED is available only on the new boards (for ESP32C3, S2, S3,...) but not on ESP32 boards, hence the warning.

**Comment by randallgyebi** [comment]
Thanks
