### ISSUE TITLE
CMakelist.txt include "cloud.c"

### ISSUE THREAD

**Issue by kangbudz** [espressif/esp-jumpstart#2]
While build this  jumpstart sample use " make app" , build will pass normally. try to use build command "idf.py app" , then result will fail.
Build error message :
Call Stack (most recent call first):
 ```
 /home/budipras/esp/esp-idf/tools/cmake/component.cmake:500 (idf_component_register)
  main/CMakeLists.txt:8 (register_component)
```

it seems issue caused by "cloud.c" in CMakelist.txt of main folder. While change to "cloud_aws.c" then issue solve, but another issue appears ::

`Scanning dependencies of target __idf_main
[100%] Linking CXX static library libmain.a
[100%] Built target __idf_main
[100%] Generating ld/esp32.project.ld
[100%] Built target __ldgen_output_esp32.project.ld
[100%] Built target __idf_build_target
[100%] Linking CXX executable 7_mfg.elf
/home/budipras/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/esp32/libesp32.a(cpu_start.c.obj):(.literal.main_task+0x18): undefined reference to `app_main'
/home/budipras/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/esp32/libesp32.a(cpu_start.c.obj): in function `main_task':
/home/budipras/esp/esp-idf/components/esp32/cpu_start.c:513: undefined reference to `app_main'
collect2: error: ld returned 1 exit status
CMakeFiles/7_mfg.elf.dir/build.make:333: recipe for target '7_mfg.elf' failed
make[3]: *** [7_mfg.elf] Error 1
CMakeFiles/Makefile2:678: recipe for target 'CMakeFiles/7_mfg.elf.dir/all' failed
make[2]: *** [CMakeFiles/7_mfg.elf.dir/all] Error 2
CMakeFiles/Makefile2:1305: recipe for target 'CMakeFiles/app.dir/rule' failed
make[1]: *** [CMakeFiles/app.dir/rule] Error 2
Makefile:645: recipe for target 'app' failed
make: *** [app] Error 2
make failed with exit code 2`

Any idea to solve idf.py build?

**Comment by shahpiyushv** [comment]
@kangbudz , sorry for the late reply. The esp-jumpstart was recently rebased to IDF v3.3 and the cmake failures have been fixed. Please check again

**Comment by shahpiyushv** [comment]
Closing this issue as it has been addressed.
