### ISSUE TITLE
404s on espressif.com published version of these docs

### ISSUE THREAD

**Issue by hamishcunningham** [espressif/esp-jumpstart#4]
Some of the published version works, but some doesn't, e.g.:
https://docs.espressif.com/projects/esp-jumpstart/en/latest/remotecontrol.html
gives 404 at present.

HTH, best
Hamish

**Comment by shahpiyushv** [comment]
@hamishcunningham , we are facing some issues on the server side. Please try refreshing a few times. The page should load eventually.

**Comment by ameyinamdar** [comment]
@hamishcunningham are you still facing this issue? Please reopen if you still see the problem.
