### ISSUE TITLE
Setup problems.

### ISSUE THREAD

**Issue by monkeytronics** [espressif/esp-jumpstart#5]
Hi. I'm having difficulties with the very first steps. Running on windows 10. I followed the msys32 setup procedure from https://docs.espressif.com/projects/esp-idf/en/release-v3.3/get-started/index.html. I can successfully run the standard hello world demo from the esp-idf examples folder.  

However, when I try to run the first example in the jumpstart, I receive the following errors:

```
$ make flash
Toolchain path: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a5
Compiler version: 5.2.0
Python requirements from C:/msys32/home/thebi/esp/esp-idf/requirements.txt are satisfied.

Project is not inside a git repository, will not use 'git describe' to determine PROJECT_VER.
App "1_hello_world" version: 1
CC build/app_update/esp_app_desc.o
AR build/app_update/libapp_update.a
Generating libapp_update.a.sections_info
Generating esp32.project.ld
LD build/1_hello_world.elf
c:/msys32/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lmicro-ecc
c:/msys32/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lmqtt
c:/msys32/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lnewlib
c:/msys32/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lnimble
c:/msys32/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lnvs_flash
collect2.exe: error: ld returned 1 exit status
make: *** [C:/msys32/home/thebi/esp/esp-idf/make/project.mk:483: /home/thebi/esp/1_hello_world/build/1_hello_world.elf] Error 1
```
I've followed the guide to the letter I believe. I copied the git clone exactly with the --recursive flag. Any clues what these erros mean.

Update
-----------
I completely erased everything and rebuilt. It now works perfectly. Well done Espressif!

**Comment by pn21** [comment]
I am having a similar problem while using Eclipse IDE. I tried the option of "Open projects thru File System" in eclipse ide and opened the "1_Hello_World" example within the "esp-Jumpstart" folder but it does not give me the option to compile the project. Am I doing it correctly or do I need to open the first example "1_Hello_world" as a new project? Appreciate any help.
