### ISSUE TITLE
how to configure  esp-jumpstart/5_cloud with the aws files?

### ISSUE THREAD

**Issue by SimonAndro** [espressif/esp-jumpstart#7]
I get this error on building; 
In file included from ../main/cloud_aws.c:16:
../main/aws_custom_utils.h:4:10: fatal error: aws_iot_error.h: No such file or directory
 #include "aws_iot_error.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Thanks in advance

**Comment by shahpiyushv** [comment]
@SimonAndro , Seems that the esp-aws-iot submodule is absent. Did you miss using the --recursive option while cloning?

```
$ git clone --recursive https://github.com/espressif/esp-jumpstart.git
```

You can fetch this missing submodule now by using the below in esp-jumpstart:

```
$ git submodule update --init --recursive
```

**Comment by SimonAndro** [comment]
I have cloned again and it works fine now. Thanks very much.
