### ISSUE TITLE
Issue with wifi_provisioning/manager.h library on ESP8266

### ISSUE THREAD

**Issue by piyush-saurabh** [espressif/esp-jumpstart#9]
I am trying to follow along the ESP Jumpstart guide and working on [Unified Provisioning](https://docs.espressif.com/projects/esp-jumpstart/en/latest/networkconfig.html) part using ESP8266. Everything was working correctly untill I came to Unified Provisioning section. On running the code under [4_network_config](https://github.com/espressif/esp-jumpstart/tree/master/4_network_config), I am getting the below error  

`CC build/main/app_main.o
/<directory>/app_main.c:17:10: fatal error: wifi_provisioning/manager.h: No such file or directory
 #include <wifi_provisioning/manager.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/<directory>/ESP8266_RTOS_SDK/make/component_wrapper.mk:292: app_main.o] Error 1
make: *** [/<directory>/ESP8266_RTOS_SDK/make/project.mk:571: component-main-build] Error 2`

I have all the required files in /<directory>/ESP8266_RTOS_SDK/components/wifi_provisioning/include/wifi_provisioning/ which can also be confirmed by using "Go to Definition" feature of vscode.

The environment for ESP8266 was setup by following the guide https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/index.html

**Comment by piyush-saurabh** [comment]
Closing this, since for ESP8266, conn_mgr_prov.h needs to be used

**Comment by ameyinamdar** [comment]
Hi @piyush-saurabh can you please confirm that you're using platform/esp8266 branch of esp-jumpstart and using the right commit ID of ESP8266_RTOS_SDK (93e3a3f5424e76def8afb3c41e625471490c056b) as described in the documentation [https://github.com/espressif/esp-jumpstart/tree/platform/esp8266](https://github.com/espressif/esp-jumpstart/tree/platform/esp8266)
